services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - "DatabaseSettings__ConnectionString=Server=db;Port=3306;Database=db;Uid=root;Pwd=my-secret-pw;"
      - "DatabaseSettings__DBProvider=mysql"
#      - "ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword"
#      - "ASPNETCORE_Kestrel__Certificates__Default__Path=~/.aspnet/https/cges.WebApi.Host.pfx"
    ports:
      - "5050:5050"
      - "5060:5060"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  db:
    image: "mysql:latest"
    container_name: db
    environment:
      - "MYSQL_ROOT_PASSWORD=my-secret-pw"
      - "MYSQL_DATABASE=db"
    ports:
      - "3307:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=my-secret-pw --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
